version: '3.9'

services:
  db:
    image: postgres
    container_name: "${CONTAINER_DB_NAME}"
    ports:
      - '${APP_DB_PORT}:5432'
    environment:
      POSTGRES_USER: "${APP_DB_USERNAME}"
      POSTGRES_PASSWORD: "${APP_DB_PASSWORD}"
      POSTGRES_DB: "${APP_DB_PG}"
      TZ: Europe/Moscow