version: '3.9'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6464
      POSTGRES_DB: pet
      TZ: Europe/Moscow